# Generated by Django 5.0.4 on 2024-04-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=13, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=40)),
                ('mark', models.IntegerField(default=0)),
                ('outoff', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('passfail', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Summery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=13, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('totalmark', models.IntegerField(default=0, null=True)),
                ('totalotoff', models.IntegerField(default=0, null=True)),
                ('totalpercentage', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
