# Generated by Django 5.0.4 on 2024-04-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('subject', models.CharField(max_length=100)),
                ('mark', models.IntegerField()),
                ('out_of', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Stud',
        ),
        migrations.DeleteModel(
            name='Summery',
        ),
    ]
